//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5485
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace fiasxml.Entityes
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Rooms
    {

        private RoomsRoom[] roomField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Room")]
        public RoomsRoom[] Room
        {
            get
            {
                return this.roomField;
            }
            set
            {
                this.roomField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomsRoom
    {

        private string rOOMGUIDField;

        private string fLATNUMBERField;

        private int fLATTYPEField;

        private string rOOMNUMBERField;

        private int rOOMTYPEField;

        private bool rOOMTYPEFieldSpecified;

        private string rEGIONCODEField;

        private string pOSTALCODEField;

        private System.DateTime uPDATEDATEField;

        private string hOUSEGUIDField;

        private string rOOMIDField;

        private string pREVIDField;

        private string nEXTIDField;

        private System.DateTime sTARTDATEField;

        private System.DateTime eNDDATEField;

        private sbyte lIVESTATUSField;

        private string nORMDOCField;

        private string oPERSTATUSField;

        private string cADNUMField;

        private string rOOMCADNUMField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ROOMGUID
        {
            get
            {
                return this.rOOMGUIDField;
            }
            set
            {
                this.rOOMGUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FLATNUMBER
        {
            get
            {
                return this.fLATNUMBERField;
            }
            set
            {
                this.fLATNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FLATTYPE
        {
            get
            {
                return this.fLATTYPEField;
            }
            set
            {
                this.fLATTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ROOMNUMBER
        {
            get
            {
                return this.rOOMNUMBERField;
            }
            set
            {
                this.rOOMNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ROOMTYPE
        {
            get
            {
                return this.rOOMTYPEField;
            }
            set
            {
                this.rOOMTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ROOMTYPESpecified
        {
            get
            {
                return this.rOOMTYPEFieldSpecified;
            }
            set
            {
                this.rOOMTYPEFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string REGIONCODE
        {
            get
            {
                return this.rEGIONCODEField;
            }
            set
            {
                this.rEGIONCODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string POSTALCODE
        {
            get
            {
                return this.pOSTALCODEField;
            }
            set
            {
                this.pOSTALCODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime UPDATEDATE
        {
            get
            {
                return this.uPDATEDATEField;
            }
            set
            {
                this.uPDATEDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HOUSEGUID
        {
            get
            {
                return this.hOUSEGUIDField;
            }
            set
            {
                this.hOUSEGUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ROOMID
        {
            get
            {
                return this.rOOMIDField;
            }
            set
            {
                this.rOOMIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PREVID
        {
            get
            {
                return this.pREVIDField;
            }
            set
            {
                this.pREVIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NEXTID
        {
            get
            {
                return this.nEXTIDField;
            }
            set
            {
                this.nEXTIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime STARTDATE
        {
            get
            {
                return this.sTARTDATEField;
            }
            set
            {
                this.sTARTDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ENDDATE
        {
            get
            {
                return this.eNDDATEField;
            }
            set
            {
                this.eNDDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte LIVESTATUS
        {
            get
            {
                return this.lIVESTATUSField;
            }
            set
            {
                this.lIVESTATUSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NORMDOC
        {
            get
            {
                return this.nORMDOCField;
            }
            set
            {
                this.nORMDOCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string OPERSTATUS
        {
            get
            {
                return this.oPERSTATUSField;
            }
            set
            {
                this.oPERSTATUSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CADNUM
        {
            get
            {
                return this.cADNUMField;
            }
            set
            {
                this.cADNUMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ROOMCADNUM
        {
            get
            {
                return this.rOOMCADNUMField;
            }
            set
            {
                this.rOOMCADNUMField = value;
            }
        }
    }
}
