//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fiasxml.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressObjectType
    {
        public int LEVEL { get; set; }
        public string SCNAME { get; set; }
        public string SOCRNAME { get; set; }
        public string KOD_T_ST { get; set; }
    }
}
