//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fiasxml.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentStatus
    {
        public int CURENTSTID { get; set; }
        public string NAME { get; set; }
    }
}
