//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fiasxml.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public string POSTALCODE { get; set; }
        public string IFNSFL { get; set; }
        public string TERRIFNSFL { get; set; }
        public string IFNSUL { get; set; }
        public string TERRIFNSUL { get; set; }
        public string OKATO { get; set; }
        public string OKTMO { get; set; }
        public System.DateTime UPDATEDATE { get; set; }
        public string HOUSENUM { get; set; }
        public long ESTSTATUS { get; set; }
        public string BUILDNUM { get; set; }
        public string STRUCNUM { get; set; }
        public Nullable<long> STRSTATUS { get; set; }
        public System.Guid HOUSEID { get; set; }
        public Nullable<System.Guid> HOUSEGUID { get; set; }
        public Nullable<System.Guid> AOGUID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public long STATSTATUS { get; set; }
        public Nullable<System.Guid> NORMDOC { get; set; }
        public long COUNTER { get; set; }
        public string CADNUM { get; set; }
        public int DIVTYPE { get; set; }
    }
}
