//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fiasxml.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Landmark
    {
        public string LOCATION { get; set; }
        public string REGIONCODE { get; set; }
        public string POSTALCODE { get; set; }
        public string IFNSFL { get; set; }
        public string TERRIFNSFL { get; set; }
        public string IFNSUL { get; set; }
        public string TERRIFNSUL { get; set; }
        public string OKATO { get; set; }
        public string OKTMO { get; set; }
        public System.DateTime UPDATEDATE { get; set; }
        public string LANDID { get; set; }
        public string LANDGUID { get; set; }
        public Nullable<System.Guid> AOGUID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public Nullable<System.Guid> NORMDOC { get; set; }
        public string CADNUM { get; set; }
    }
}
