//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fiasxml.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ttt2Entities2 : DbContext
    {
        public ttt2Entities2()
            : base("name=ttt2Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<House> House { get; set; }
    
        public virtual int insertHouse(string pOSTALCODE, string iFNSFL, string tERRIFNSFL, string iFNSUL, string tERRIFNSUL, string oKATO, string oKTMO, Nullable<System.DateTime> uPDATEDATE, string hOUSENUM, Nullable<long> eSTSTATUS, string bUILDNUM, string sTRUCNUM, Nullable<long> sTRSTATUS, Nullable<System.Guid> hOUSEID, Nullable<System.Guid> hOUSEGUID, Nullable<System.Guid> aOGUID, Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE, Nullable<long> sTATSTATUS, Nullable<System.Guid> nORMDOC, Nullable<long> cOUNTER, string cADNUM, Nullable<int> dIVTYPE)
        {
            var pOSTALCODEParameter = pOSTALCODE != null ?
                new ObjectParameter("POSTALCODE", pOSTALCODE) :
                new ObjectParameter("POSTALCODE", typeof(string));
    
            var iFNSFLParameter = iFNSFL != null ?
                new ObjectParameter("IFNSFL", iFNSFL) :
                new ObjectParameter("IFNSFL", typeof(string));
    
            var tERRIFNSFLParameter = tERRIFNSFL != null ?
                new ObjectParameter("TERRIFNSFL", tERRIFNSFL) :
                new ObjectParameter("TERRIFNSFL", typeof(string));
    
            var iFNSULParameter = iFNSUL != null ?
                new ObjectParameter("IFNSUL", iFNSUL) :
                new ObjectParameter("IFNSUL", typeof(string));
    
            var tERRIFNSULParameter = tERRIFNSUL != null ?
                new ObjectParameter("TERRIFNSUL", tERRIFNSUL) :
                new ObjectParameter("TERRIFNSUL", typeof(string));
    
            var oKATOParameter = oKATO != null ?
                new ObjectParameter("OKATO", oKATO) :
                new ObjectParameter("OKATO", typeof(string));
    
            var oKTMOParameter = oKTMO != null ?
                new ObjectParameter("OKTMO", oKTMO) :
                new ObjectParameter("OKTMO", typeof(string));
    
            var uPDATEDATEParameter = uPDATEDATE.HasValue ?
                new ObjectParameter("UPDATEDATE", uPDATEDATE) :
                new ObjectParameter("UPDATEDATE", typeof(System.DateTime));
    
            var hOUSENUMParameter = hOUSENUM != null ?
                new ObjectParameter("HOUSENUM", hOUSENUM) :
                new ObjectParameter("HOUSENUM", typeof(string));
    
            var eSTSTATUSParameter = eSTSTATUS.HasValue ?
                new ObjectParameter("ESTSTATUS", eSTSTATUS) :
                new ObjectParameter("ESTSTATUS", typeof(long));
    
            var bUILDNUMParameter = bUILDNUM != null ?
                new ObjectParameter("BUILDNUM", bUILDNUM) :
                new ObjectParameter("BUILDNUM", typeof(string));
    
            var sTRUCNUMParameter = sTRUCNUM != null ?
                new ObjectParameter("STRUCNUM", sTRUCNUM) :
                new ObjectParameter("STRUCNUM", typeof(string));
    
            var sTRSTATUSParameter = sTRSTATUS.HasValue ?
                new ObjectParameter("STRSTATUS", sTRSTATUS) :
                new ObjectParameter("STRSTATUS", typeof(long));
    
            var hOUSEIDParameter = hOUSEID.HasValue ?
                new ObjectParameter("HOUSEID", hOUSEID) :
                new ObjectParameter("HOUSEID", typeof(System.Guid));
    
            var hOUSEGUIDParameter = hOUSEGUID.HasValue ?
                new ObjectParameter("HOUSEGUID", hOUSEGUID) :
                new ObjectParameter("HOUSEGUID", typeof(System.Guid));
    
            var aOGUIDParameter = aOGUID.HasValue ?
                new ObjectParameter("AOGUID", aOGUID) :
                new ObjectParameter("AOGUID", typeof(System.Guid));
    
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            var sTATSTATUSParameter = sTATSTATUS.HasValue ?
                new ObjectParameter("STATSTATUS", sTATSTATUS) :
                new ObjectParameter("STATSTATUS", typeof(long));
    
            var nORMDOCParameter = nORMDOC.HasValue ?
                new ObjectParameter("NORMDOC", nORMDOC) :
                new ObjectParameter("NORMDOC", typeof(System.Guid));
    
            var cOUNTERParameter = cOUNTER.HasValue ?
                new ObjectParameter("COUNTER", cOUNTER) :
                new ObjectParameter("COUNTER", typeof(long));
    
            var cADNUMParameter = cADNUM != null ?
                new ObjectParameter("CADNUM", cADNUM) :
                new ObjectParameter("CADNUM", typeof(string));
    
            var dIVTYPEParameter = dIVTYPE.HasValue ?
                new ObjectParameter("DIVTYPE", dIVTYPE) :
                new ObjectParameter("DIVTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertHouse", pOSTALCODEParameter, iFNSFLParameter, tERRIFNSFLParameter, iFNSULParameter, tERRIFNSULParameter, oKATOParameter, oKTMOParameter, uPDATEDATEParameter, hOUSENUMParameter, eSTSTATUSParameter, bUILDNUMParameter, sTRUCNUMParameter, sTRSTATUSParameter, hOUSEIDParameter, hOUSEGUIDParameter, aOGUIDParameter, sTARTDATEParameter, eNDDATEParameter, sTATSTATUSParameter, nORMDOCParameter, cOUNTERParameter, cADNUMParameter, dIVTYPEParameter);
        }
    
        public virtual int insertHouse1(string pOSTALCODE, string iFNSFL, string tERRIFNSFL, string iFNSUL, string tERRIFNSUL, string oKATO, string oKTMO, Nullable<System.DateTime> uPDATEDATE, string hOUSENUM, Nullable<long> eSTSTATUS, string bUILDNUM, string sTRUCNUM, Nullable<long> sTRSTATUS, Nullable<System.Guid> hOUSEID, Nullable<System.Guid> hOUSEGUID, Nullable<System.Guid> aOGUID, Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE, Nullable<long> sTATSTATUS, Nullable<System.Guid> nORMDOC, Nullable<long> cOUNTER, string cADNUM, Nullable<int> dIVTYPE)
        {
            var pOSTALCODEParameter = pOSTALCODE != null ?
                new ObjectParameter("POSTALCODE", pOSTALCODE) :
                new ObjectParameter("POSTALCODE", typeof(string));
    
            var iFNSFLParameter = iFNSFL != null ?
                new ObjectParameter("IFNSFL", iFNSFL) :
                new ObjectParameter("IFNSFL", typeof(string));
    
            var tERRIFNSFLParameter = tERRIFNSFL != null ?
                new ObjectParameter("TERRIFNSFL", tERRIFNSFL) :
                new ObjectParameter("TERRIFNSFL", typeof(string));
    
            var iFNSULParameter = iFNSUL != null ?
                new ObjectParameter("IFNSUL", iFNSUL) :
                new ObjectParameter("IFNSUL", typeof(string));
    
            var tERRIFNSULParameter = tERRIFNSUL != null ?
                new ObjectParameter("TERRIFNSUL", tERRIFNSUL) :
                new ObjectParameter("TERRIFNSUL", typeof(string));
    
            var oKATOParameter = oKATO != null ?
                new ObjectParameter("OKATO", oKATO) :
                new ObjectParameter("OKATO", typeof(string));
    
            var oKTMOParameter = oKTMO != null ?
                new ObjectParameter("OKTMO", oKTMO) :
                new ObjectParameter("OKTMO", typeof(string));
    
            var uPDATEDATEParameter = uPDATEDATE.HasValue ?
                new ObjectParameter("UPDATEDATE", uPDATEDATE) :
                new ObjectParameter("UPDATEDATE", typeof(System.DateTime));
    
            var hOUSENUMParameter = hOUSENUM != null ?
                new ObjectParameter("HOUSENUM", hOUSENUM) :
                new ObjectParameter("HOUSENUM", typeof(string));
    
            var eSTSTATUSParameter = eSTSTATUS.HasValue ?
                new ObjectParameter("ESTSTATUS", eSTSTATUS) :
                new ObjectParameter("ESTSTATUS", typeof(long));
    
            var bUILDNUMParameter = bUILDNUM != null ?
                new ObjectParameter("BUILDNUM", bUILDNUM) :
                new ObjectParameter("BUILDNUM", typeof(string));
    
            var sTRUCNUMParameter = sTRUCNUM != null ?
                new ObjectParameter("STRUCNUM", sTRUCNUM) :
                new ObjectParameter("STRUCNUM", typeof(string));
    
            var sTRSTATUSParameter = sTRSTATUS.HasValue ?
                new ObjectParameter("STRSTATUS", sTRSTATUS) :
                new ObjectParameter("STRSTATUS", typeof(long));
    
            var hOUSEIDParameter = hOUSEID.HasValue ?
                new ObjectParameter("HOUSEID", hOUSEID) :
                new ObjectParameter("HOUSEID", typeof(System.Guid));
    
            var hOUSEGUIDParameter = hOUSEGUID.HasValue ?
                new ObjectParameter("HOUSEGUID", hOUSEGUID) :
                new ObjectParameter("HOUSEGUID", typeof(System.Guid));
    
            var aOGUIDParameter = aOGUID.HasValue ?
                new ObjectParameter("AOGUID", aOGUID) :
                new ObjectParameter("AOGUID", typeof(System.Guid));
    
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            var sTATSTATUSParameter = sTATSTATUS.HasValue ?
                new ObjectParameter("STATSTATUS", sTATSTATUS) :
                new ObjectParameter("STATSTATUS", typeof(long));
    
            var nORMDOCParameter = nORMDOC.HasValue ?
                new ObjectParameter("NORMDOC", nORMDOC) :
                new ObjectParameter("NORMDOC", typeof(System.Guid));
    
            var cOUNTERParameter = cOUNTER.HasValue ?
                new ObjectParameter("COUNTER", cOUNTER) :
                new ObjectParameter("COUNTER", typeof(long));
    
            var cADNUMParameter = cADNUM != null ?
                new ObjectParameter("CADNUM", cADNUM) :
                new ObjectParameter("CADNUM", typeof(string));
    
            var dIVTYPEParameter = dIVTYPE.HasValue ?
                new ObjectParameter("DIVTYPE", dIVTYPE) :
                new ObjectParameter("DIVTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertHouse1", pOSTALCODEParameter, iFNSFLParameter, tERRIFNSFLParameter, iFNSULParameter, tERRIFNSULParameter, oKATOParameter, oKTMOParameter, uPDATEDATEParameter, hOUSENUMParameter, eSTSTATUSParameter, bUILDNUMParameter, sTRUCNUMParameter, sTRSTATUSParameter, hOUSEIDParameter, hOUSEGUIDParameter, aOGUIDParameter, sTARTDATEParameter, eNDDATEParameter, sTATSTATUSParameter, nORMDOCParameter, cOUNTERParameter, cADNUMParameter, dIVTYPEParameter);
        }
    
        public virtual int insertHouse11(string pOSTALCODE, string iFNSFL, string tERRIFNSFL, string iFNSUL, string tERRIFNSUL, string oKATO, string oKTMO, Nullable<System.DateTime> uPDATEDATE, string hOUSENUM, Nullable<long> eSTSTATUS, string bUILDNUM, string sTRUCNUM, Nullable<long> sTRSTATUS, Nullable<System.Guid> hOUSEID, Nullable<System.Guid> hOUSEGUID, Nullable<System.Guid> aOGUID, Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE, Nullable<long> sTATSTATUS, Nullable<System.Guid> nORMDOC, Nullable<long> cOUNTER, string cADNUM, Nullable<int> dIVTYPE)
        {
            var pOSTALCODEParameter = pOSTALCODE != null ?
                new ObjectParameter("POSTALCODE", pOSTALCODE) :
                new ObjectParameter("POSTALCODE", typeof(string));
    
            var iFNSFLParameter = iFNSFL != null ?
                new ObjectParameter("IFNSFL", iFNSFL) :
                new ObjectParameter("IFNSFL", typeof(string));
    
            var tERRIFNSFLParameter = tERRIFNSFL != null ?
                new ObjectParameter("TERRIFNSFL", tERRIFNSFL) :
                new ObjectParameter("TERRIFNSFL", typeof(string));
    
            var iFNSULParameter = iFNSUL != null ?
                new ObjectParameter("IFNSUL", iFNSUL) :
                new ObjectParameter("IFNSUL", typeof(string));
    
            var tERRIFNSULParameter = tERRIFNSUL != null ?
                new ObjectParameter("TERRIFNSUL", tERRIFNSUL) :
                new ObjectParameter("TERRIFNSUL", typeof(string));
    
            var oKATOParameter = oKATO != null ?
                new ObjectParameter("OKATO", oKATO) :
                new ObjectParameter("OKATO", typeof(string));
    
            var oKTMOParameter = oKTMO != null ?
                new ObjectParameter("OKTMO", oKTMO) :
                new ObjectParameter("OKTMO", typeof(string));
    
            var uPDATEDATEParameter = uPDATEDATE.HasValue ?
                new ObjectParameter("UPDATEDATE", uPDATEDATE) :
                new ObjectParameter("UPDATEDATE", typeof(System.DateTime));
    
            var hOUSENUMParameter = hOUSENUM != null ?
                new ObjectParameter("HOUSENUM", hOUSENUM) :
                new ObjectParameter("HOUSENUM", typeof(string));
    
            var eSTSTATUSParameter = eSTSTATUS.HasValue ?
                new ObjectParameter("ESTSTATUS", eSTSTATUS) :
                new ObjectParameter("ESTSTATUS", typeof(long));
    
            var bUILDNUMParameter = bUILDNUM != null ?
                new ObjectParameter("BUILDNUM", bUILDNUM) :
                new ObjectParameter("BUILDNUM", typeof(string));
    
            var sTRUCNUMParameter = sTRUCNUM != null ?
                new ObjectParameter("STRUCNUM", sTRUCNUM) :
                new ObjectParameter("STRUCNUM", typeof(string));
    
            var sTRSTATUSParameter = sTRSTATUS.HasValue ?
                new ObjectParameter("STRSTATUS", sTRSTATUS) :
                new ObjectParameter("STRSTATUS", typeof(long));
    
            var hOUSEIDParameter = hOUSEID.HasValue ?
                new ObjectParameter("HOUSEID", hOUSEID) :
                new ObjectParameter("HOUSEID", typeof(System.Guid));
    
            var hOUSEGUIDParameter = hOUSEGUID.HasValue ?
                new ObjectParameter("HOUSEGUID", hOUSEGUID) :
                new ObjectParameter("HOUSEGUID", typeof(System.Guid));
    
            var aOGUIDParameter = aOGUID.HasValue ?
                new ObjectParameter("AOGUID", aOGUID) :
                new ObjectParameter("AOGUID", typeof(System.Guid));
    
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            var sTATSTATUSParameter = sTATSTATUS.HasValue ?
                new ObjectParameter("STATSTATUS", sTATSTATUS) :
                new ObjectParameter("STATSTATUS", typeof(long));
    
            var nORMDOCParameter = nORMDOC.HasValue ?
                new ObjectParameter("NORMDOC", nORMDOC) :
                new ObjectParameter("NORMDOC", typeof(System.Guid));
    
            var cOUNTERParameter = cOUNTER.HasValue ?
                new ObjectParameter("COUNTER", cOUNTER) :
                new ObjectParameter("COUNTER", typeof(long));
    
            var cADNUMParameter = cADNUM != null ?
                new ObjectParameter("CADNUM", cADNUM) :
                new ObjectParameter("CADNUM", typeof(string));
    
            var dIVTYPEParameter = dIVTYPE.HasValue ?
                new ObjectParameter("DIVTYPE", dIVTYPE) :
                new ObjectParameter("DIVTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertHouse11", pOSTALCODEParameter, iFNSFLParameter, tERRIFNSFLParameter, iFNSULParameter, tERRIFNSULParameter, oKATOParameter, oKTMOParameter, uPDATEDATEParameter, hOUSENUMParameter, eSTSTATUSParameter, bUILDNUMParameter, sTRUCNUMParameter, sTRSTATUSParameter, hOUSEIDParameter, hOUSEGUIDParameter, aOGUIDParameter, sTARTDATEParameter, eNDDATEParameter, sTATSTATUSParameter, nORMDOCParameter, cOUNTERParameter, cADNUMParameter, dIVTYPEParameter);
        }
    }
}
