//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fiasxml.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public Nullable<System.Guid> AOGUID { get; set; }
        public string FORMALNAME { get; set; }
        public string REGIONCODE { get; set; }
        public string AUTOCODE { get; set; }
        public string AREACODE { get; set; }
        public string CITYCODE { get; set; }
        public string CTARCODE { get; set; }
        public string PLACECODE { get; set; }
        public string STREETCODE { get; set; }
        public string EXTRCODE { get; set; }
        public string SEXTCODE { get; set; }
        public string OFFNAME { get; set; }
        public string POSTALCODE { get; set; }
        public string IFNSFL { get; set; }
        public string TERRIFNSFL { get; set; }
        public string IFNSUL { get; set; }
        public string TERRIFNSUL { get; set; }
        public string OKATO { get; set; }
        public string OKTMO { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string SHORTNAME { get; set; }
        public Nullable<int> AOLEVEL { get; set; }
        public Nullable<System.Guid> PARENTGUID { get; set; }
        public System.Guid AOID { get; set; }
        public Nullable<System.Guid> PREVID { get; set; }
        public Nullable<System.Guid> NEXTID { get; set; }
        public string CODE { get; set; }
        public string PLAINCODE { get; set; }
        public Nullable<int> ACTSTATUS { get; set; }
        public Nullable<int> CENTSTATUS { get; set; }
        public Nullable<int> OPERSTATUS { get; set; }
        public Nullable<int> CURRSTATUS { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.Guid> NORMDOC { get; set; }
        public string LIVESTATUS { get; set; }
        public string CADNUM { get; set; }
        public Nullable<int> DIVTYPE { get; set; }
        public Nullable<int> OFFNAME_NUM_TYPE { get; set; }
        public Nullable<int> OFFNAME_NUM_NUMBER { get; set; }
        public Nullable<int> OFFNAME_NUM_PREFIX { get; set; }
        public string OFFNAME_NUMBER { get; set; }
        public string OFFNAME_PREFIX { get; set; }
        public string OFFNAME_NAME { get; set; }
        public string CONVERTSTREET { get; set; }
    }
}
