//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fiasxml.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public string ROOMGUID { get; set; }
        public string FLATNUMBER { get; set; }
        public int FLATTYPE { get; set; }
        public string ROOMNUMBER { get; set; }
        public Nullable<int> ROOMTYPE { get; set; }
        public string REGIONCODE { get; set; }
        public string POSTALCODE { get; set; }
        public System.DateTime UPDATEDATE { get; set; }
        public string HOUSEGUID { get; set; }
        public string ROOMID { get; set; }
        public string PREVID { get; set; }
        public string NEXTID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public bool LIVESTATUS { get; set; }
        public string NORMDOC { get; set; }
        public long OPERSTATUS { get; set; }
        public string CADNUM { get; set; }
        public string ROOMCADNUM { get; set; }
    }
}
