//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fiasxml.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stead
    {
        public string STEADGUID { get; set; }
        public string NUMBER { get; set; }
        public string REGIONCODE { get; set; }
        public string POSTALCODE { get; set; }
        public string IFNSFL { get; set; }
        public string TERRIFNSFL { get; set; }
        public string IFNSUL { get; set; }
        public string TERRIFNSUL { get; set; }
        public string OKATO { get; set; }
        public string OKTMO { get; set; }
        public System.DateTime UPDATEDATE { get; set; }
        public string PARENTGUID { get; set; }
        public string STEADID { get; set; }
        public string PREVID { get; set; }
        public string NEXTID { get; set; }
        public long OPERSTATUS { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public string NORMDOC { get; set; }
        public int LIVESTATUS { get; set; }
        public string CADNUM { get; set; }
        public int DIVTYPE { get; set; }
    }
}
